# -*- coding: utf-8 -*-
"""Lamacchia Lorenzo datascience.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F4H7DeQBwhPpSHgqKTtzG_5V4WkFFtE1
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/access_electricity.csv')
display(df.head())

"""## Esplorazione iniziale: numero di dati (righe e colonne), tipo di dati (commento).


"""

print("Numero di dati e tipo di dati:", df.shape)
df.info()

"""## 4 selezioni dei dati motivate (commento per ciascuna), 2 delle quali usanto .loc[] e .iloc[]."""

df_africa = df[df['Continent'] == 'Africa'].copy()
display(df_africa.head())

"""* Seleziono le colonne per ciascun paese europeo in base all'accesso all'elettricità nel 2016
* Ne prendo le prime 5
* Uso .loc

"""

df_europe_2016 = df.loc[df['Continent'] == 'Europe', ['Country Name', '2016 [YR2016]']].copy()
display(df_europe_2016.head())

"""Seleziono le primr 10 righe con .iloc per far vedere come funziona la selezione usando il numero di indice e di colonna


"""

df_iloc_selection = df.iloc[0:11, 5:8].copy()
display(df_iloc_selection.head())

"""Seleziono le righe dove nella colonna dell'anno 2015 hanno valori più grandi di 90 accessi

"""

df_high_access_2015 = df[pd.to_numeric(df['2015 [YR2015]'], errors='coerce') > 90].copy()
display(df_high_access_2015.head())

"""##  2 riodinamenti (1 ascendente e 1 discendente) di due variabili a scelta motivate (commento per ciascuno)

Ordino gli accessi dell'anno 2015 dal più grande al più piccolo e ne stampo le prime 5 usando head(), per vedere quali paesi hanno avuto accesso all'elettricità maggiormente nel 2015
"""

df_high_access_2015_asc = df_high_access_2015.sort_values(by='2015 [YR2015]', ascending=True)
display(df_high_access_2015_asc.head())

"""Converto in int i valori della colonna dell'anno 2016, del continente africano, elimino le righe vuote,
e ordino le righe in maniera decrescente

"""

df_africa['2016 [YR2016]'] = pd.to_numeric(df_africa['2016 [YR2016]'], errors='coerce')
df_africa_cleaned = df_africa.dropna(subset=['2016 [YR2016]']).copy()

df_africa_desc = df_africa_cleaned.sort_values(by='2016 [YR2016]', ascending=False)
display(df_africa_desc.head())

"""## 1 nuova colonna creata usando apply e lambda (commento).

Aggiungo una colonna in più dove riga per riga fa la media per tutti gli anni, crendo prima una lista con le colonne dei campi degli anni, mettendo year nel range degli anni che ci sono (dal 2012 al 2017)
"""

year_columns = [f'{year} [YR{year}]' for year in range(2012, 2017)]
# Convert year columns to numeric, coercing errors to NaN
for col in year_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['media tra tutti gli anni'] = df[year_columns].mean(axis=1)
display(df.head())

"""## 5 grafici comprensivi di titolo, labels e interpretazione (commento per ciascuno) di cui almeno 1 boxplot, 1 istogramma e 1 scatterplot usando sia Matplotlib che Seaborn.

importo matplotlib e seaborn
"""

import matplotlib.pyplot as plt
import seaborn as sns

"""Questo grafico mostra la distribuzione dell'accesso medio all'elettricità (tra il 2012 e il 2016) tra tutti i paesi presenti nel dataset. L'ho colorato in verde acqua



"""

plt.figure(figsize=(10, 6))
sns.boxplot(x=df['media tra tutti gli anni'], color='aquamarine') # Verde acqua
plt.title('Distribution of Average Electricity Access (2012-2016)')
plt.xlabel('Average Access (% of population)')
plt.show()

"""Questo istogramma mostra la distribuzione dell'accesso medio all'elettricità (tra il 2012 e il 2016), suddivisa per continente. Possiamo osservare come la distribuzione vari tra i diversi continenti, con alcuni che mostrano un accesso prevalentemente alto e altri con una maggiore concentrazione di paesi con accesso inferiore."""

plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='media tra tutti gli anni', hue='Continent', multiple='stack', bins=20, edgecolor='black')
plt.title('Histogram of Average Electricity Access (2012-2016) by Continent')
plt.xlabel('Average Access (% of population)')
plt.ylabel('Frequency')
plt.show()

"""Questo scatterplot mostra la relazione tra l'accesso all'elettricità nel 2012 e nel 2016, con colori diversi in base al continente. Si può osservare una forte correlazione positiva, indicando che i paesi con un accesso elevato nel 2012 tendono ad avere un accesso elevato anche nel 2016."""

plt.figure(figsize=(10, 6))
sns.scatterplot(x=df['2012 [YR2012]'], y=df['2016 [YR2016]'], hue='Continent', data=df)
plt.title('Electricity Access in 2016 vs 2012 by Continent')
plt.xlabel('Electricity Access (% of population) in 2012')
plt.ylabel('Electricity Access (% of population) in 2016')
plt.show()

"""Questo scatterplot mostra la relazione tra l'accesso all'elettricità nel 2012 e nel 2016 specificamente per i paesi africani.  Per identificare se ci sono paesi africani che hanno fatto progressi significativi nell'aumentare l'accesso all'elettricità tra il 2012 e il 2016."""

plt.figure(figsize=(10, 6))
sns.scatterplot(x=df_africa_cleaned['2012 [YR2012]'], y=df_africa_cleaned['2016 [YR2016]'])
plt.title('Electricity Access in Africa: 2016 vs 2012')
plt.xlabel('Electricity Access (% of population) in 2012')
plt.ylabel('Electricity Access (% of population) in 2016')
plt.show()

"""Questo istogramma mostra la distribuzione della percentuale di popolazione con accesso all'elettricità nei paesi africani nel 2016. L'asse orizzontale rappresenta le percentuali di accesso all'elettricità, mentre l'asse verticale indica il numero di paesi per ciascun intervallo di percentuale. I colori diversi per ogni barra aiutano a distinguere visivamente gli intervalli."""

plt.figure(figsize=(10, 6))
# Get the counts and bins for the histogram
counts, bins, patches = plt.hist(df_africa_cleaned['2016 [YR2016]'].dropna(), bins=20, edgecolor='black')

# Assign a different color to each bar
colors = plt.cm.viridis(counts / max(counts)) # Using a colormap based on frequency
for patch, color in zip(patches, colors):
    patch.set_facecolor(color)

plt.title('Distribution of Electricity Access in Africa (2016)')
plt.xlabel('Electricity Access (% of population)')
plt.ylabel('Frequency')
plt.show()

"""## Commento conclusivo che comprenda una riassunto di ciò che si è scoperto ed futuri sviluppi.

Questa analisi preliminare sui dati di accesso all'elettricità ha rivelato diverse tendenze interessanti tra il 2012 e il 2016. Abbiamo osservato che:

*   Esistono differenze significative nell'accesso all'elettricità tra i vari continenti, con alcuni che presentano un accesso medio più elevato di altri.
*   C'è una forte correlazione positiva tra l'accesso all'elettricità nel 2012 e nel 2016, suggerendo che i paesi con un accesso già elevato tendono a mantenerlo o migliorarlo ulteriormente.
*   Focalizzandoci sull'Africa, abbiamo potuto osservare la distribuzione dell'accesso e identificare paesi con diversi livelli di progresso.

**Futuri Sviluppi:**

Per approfondire questa analisi, si potrebbero considerare i seguenti sviluppi:

*   **Includere più anni**
*   **Esplorare altri fattori**
*   **Focus su paesi specifici**
"""